import { LegalLayout } from "./LegalLayout";

export default function PaiaManual() {
  return (
    <LegalLayout title="PAIA Manual" lastUpdated="1 March 2026">
      <h2>Manual in terms of Section 51 of the Promotion of Access to Information Act, No. 2 of 2000 ("PAIA")</h2>

      <h2>1. Introduction</h2>
      <p>
        This Manual is published in terms of Section 51 of the Promotion of Access to Information Act,
        No. 2 of 2000 ("PAIA"), as amended, and in compliance with the Protection of Personal Information
        Act, No. 4 of 2013 ("POPIA"). The purpose of this Manual is to inform the public of the
        procedures to be followed when requesting access to records held by ScribeAI (Pty) Ltd
        ("ScribeAI", "the Company").
      </p>

      <h2>2. Company Details</h2>
      <ul>
        <li><strong>Company name:</strong> ScribeAI (Pty) Ltd</li>
        <li><strong>Website:</strong> <a href="https://fant-app.com">fant-app.com</a></li>
        <li><strong>Email:</strong> <a href="mailto:info@fant-app.com">info@fant-app.com</a></li>
      </ul>

      <h2>3. Information Officer</h2>
      <p>
        The Information Officer is responsible for facilitating requests for access to information and
        for ensuring compliance with PAIA and POPIA.
      </p>
      <ul>
        <li><strong>Email:</strong> <a href="mailto:privacy@fant-app.com">privacy@fant-app.com</a></li>
      </ul>

      <h2>4. Guide on How to Use PAIA</h2>
      <p>
        The South African Human Rights Commission (SAHRC) has compiled a guide in terms of Section 10 of
        PAIA to assist persons wishing to exercise their right of access to information. The guide is
        available from the SAHRC:
      </p>
      <ul>
        <li><strong>Website:</strong> <a href="https://www.sahrc.org.za" target="_blank" rel="noopener noreferrer">www.sahrc.org.za</a></li>
        <li><strong>Tel:</strong> 011 877 3600</li>
      </ul>

      <h2>5. Records Held by ScribeAI</h2>
      <p>The following categories of records are held by ScribeAI:</p>

      <h3>5.1 Company records</h3>
      <ul>
        <li>Registration documents and memorandum of incorporation</li>
        <li>Financial records and annual financial statements</li>
        <li>Tax records and returns</li>
        <li>Minutes of meetings of directors</li>
      </ul>

      <h3>5.2 Employee records</h3>
      <ul>
        <li>Employment contracts</li>
        <li>Payroll records</li>
        <li>Employee personal information</li>
        <li>Disciplinary records</li>
      </ul>

      <h3>5.3 Client and user records</h3>
      <ul>
        <li>User account information (name, email, organisation)</li>
        <li>Subscription and payment records</li>
        <li>Audio recordings uploaded by users</li>
        <li>Transcripts, summaries, and analysis data generated by the Service</li>
        <li>Support correspondence</li>
      </ul>

      <h3>5.4 Operational records</h3>
      <ul>
        <li>Software and system architecture documentation</li>
        <li>Security policies and procedures</li>
        <li>Service level agreements with third-party providers</li>
        <li>Data processing agreements</li>
      </ul>

      <h2>6. Records Available Without a Request</h2>
      <p>The following records are freely available on our website without the need for a formal request:</p>
      <ul>
        <li>Privacy Policy</li>
        <li>Website Terms of Use</li>
        <li>Terms and Conditions</li>
        <li>This PAIA Manual</li>
        <li>Product and pricing information</li>
      </ul>

      <h2>7. Requesting Access to Records</h2>
      <p>
        To request access to a record held by ScribeAI, please follow these steps:
      </p>
      <ol>
        <li>Complete the prescribed request form (Form C, available from the Department of Justice and Constitutional Development website at <a href="https://www.justice.gov.za" target="_blank" rel="noopener noreferrer">www.justice.gov.za</a>).</li>
        <li>Submit the completed form to the Information Officer at <a href="mailto:privacy@fant-app.com">privacy@fant-app.com</a>.</li>
        <li>Pay the prescribed request fee (if applicable).</li>
        <li>The Information Officer will respond within 30 days of receipt of the request.</li>
      </ol>

      <h2>8. Grounds for Refusal</h2>
      <p>Access to records may be refused on the following grounds, as set out in PAIA:</p>
      <ul>
        <li>Protection of the privacy of a third party (Section 63)</li>
        <li>Protection of commercial information of a third party (Section 64)</li>
        <li>Protection of confidential information of a third party (Section 65)</li>
        <li>Protection of safety of individuals and property (Section 66)</li>
        <li>Records privileged from production in legal proceedings (Section 67)</li>
        <li>Commercial information of the private body (Section 68)</li>
        <li>Protection of research information (Section 69)</li>
      </ul>

      <h2>9. Remedies</h2>
      <p>
        If your request for access to information is denied, you may lodge a complaint with the Information
        Regulator or apply to a court for relief. The Information Regulator can be contacted at:
      </p>
      <ul>
        <li><strong>Website:</strong> <a href="https://inforegulator.org.za" target="_blank" rel="noopener noreferrer">inforegulator.org.za</a></li>
        <li><strong>Email:</strong> enquiries@inforegulator.org.za</li>
        <li><strong>Tel:</strong> 012 406 4818</li>
      </ul>

      <h2>10. Processing of Personal Information</h2>
      <p>In terms of Section 51(1)(c) of PAIA, read with POPIA:</p>

      <h3>10.1 Purpose of processing</h3>
      <p>ScribeAI processes personal information for the following purposes:</p>
      <ul>
        <li>Providing the AI-powered session transcription and analysis service</li>
        <li>User account management and authentication</li>
        <li>Subscription and payment processing</li>
        <li>Sending transactional emails</li>
        <li>Improving and maintaining the Service</li>
        <li>Complying with legal obligations</li>
      </ul>

      <h3>10.2 Categories of data subjects</h3>
      <ul>
        <li>Registered users of the platform</li>
        <li>Employees and contractors</li>
        <li>Clients of registered users (as referenced in session data)</li>
        <li>Website visitors</li>
      </ul>

      <h3>10.3 Recipients of personal information</h3>
      <ul>
        <li>AI service providers (OpenAI) for transcription and analysis</li>
        <li>Payment processors (PayFast, Stripe)</li>
        <li>Email service providers (Resend)</li>
        <li>Cloud infrastructure providers for hosting</li>
        <li>Regulatory authorities where required by law</li>
      </ul>

      <h3>10.4 Cross-border transfers</h3>
      <p>
        Personal information may be transferred to jurisdictions outside of South Africa where our
        service providers operate, subject to appropriate safeguards.
      </p>

      <h3>10.5 Security measures</h3>
      <p>
        ScribeAI implements appropriate technical and organisational measures to protect personal
        information, including encryption, access controls, and multi-tenant data isolation.
      </p>

      <h2>11. Updates to This Manual</h2>
      <p>
        This Manual will be updated from time to time as required by law or changes to our operations.
        The latest version will always be available on our website.
      </p>
    </LegalLayout>
  );
}
