#!/usr/bin/env bash
set -euo pipefail

PLUGIN_DIR="node_modules/capacitor-voice-recorder"

if [ ! -d "$PLUGIN_DIR" ]; then
  echo "[patch-ios-spm-plugins] $PLUGIN_DIR not found — skipping (run npm install first)."
  exit 0
fi

# ── 1. Write Package.swift so Capacitor CLI can discover the plugin via SPM ──
cat > "$PLUGIN_DIR/Package.swift" <<'SWIFT'
// swift-tools-version: 5.9
// Auto-generated by scripts/patch-ios-spm-plugins.sh
// Adds SPM support for capacitor-voice-recorder (upstream ships CocoaPods only).
import PackageDescription

let package = Package(
    name: "CapacitorVoiceRecorder",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "CapacitorVoiceRecorder",
            targets: ["CapacitorVoiceRecorderPlugin"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", from: "8.0.0")
    ],
    targets: [
        .target(
            name: "CapacitorVoiceRecorderPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm")
            ],
            path: "ios/Plugin",
            exclude: ["Info.plist"],
            publicHeadersPath: "."
        )
    ]
)
SWIFT
echo "[patch-ios-spm-plugins] Wrote $PLUGIN_DIR/Package.swift"

# ── 2. Write CAPBridgedPlugin conformance ──────────────────────────────────────
# Capacitor 8 SPM discovers plugins that conform to CAPBridgedPlugin.
# The upstream VoiceRecorder class only inherits CAPPlugin (old-style) and
# lacks the CAPBridgedPlugin protocol, so the bridge can't find it at runtime.
# We add the conformance + required properties via an extension here in the
# same module, which Swift allows.
cat > "$PLUGIN_DIR/ios/Plugin/VoiceRecorderBridged.swift" <<'SWIFT'
// Auto-generated by scripts/patch-ios-spm-plugins.sh
// Adds CAPBridgedPlugin conformance so Capacitor 8 SPM discovers this plugin.
import Capacitor

extension VoiceRecorder: CAPBridgedPlugin {
    public var identifier: String { "VoiceRecorderPlugin" }
    public var jsName: String { "VoiceRecorder" }
    public var pluginMethods: [CAPPluginMethod] {
        [
            CAPPluginMethod(name: "canDeviceVoiceRecord",             returnType: CAPPluginReturnPromise),
            CAPPluginMethod(name: "requestAudioRecordingPermission",   returnType: CAPPluginReturnPromise),
            CAPPluginMethod(name: "hasAudioRecordingPermission",       returnType: CAPPluginReturnPromise),
            CAPPluginMethod(name: "startRecording",                    returnType: CAPPluginReturnPromise),
            CAPPluginMethod(name: "stopRecording",                     returnType: CAPPluginReturnPromise),
            CAPPluginMethod(name: "pauseRecording",                    returnType: CAPPluginReturnPromise),
            CAPPluginMethod(name: "resumeRecording",                   returnType: CAPPluginReturnPromise),
            CAPPluginMethod(name: "getCurrentStatus",                  returnType: CAPPluginReturnPromise),
        ]
    }
}
SWIFT
echo "[patch-ios-spm-plugins] Wrote $PLUGIN_DIR/ios/Plugin/VoiceRecorderBridged.swift"
