#!/usr/bin/env bash
set -euo pipefail

PLUGIN_DIR="node_modules/capacitor-voice-recorder"

if [ ! -d "$PLUGIN_DIR" ]; then
  echo "[patch-ios-spm-plugins] $PLUGIN_DIR not found — skipping (run npm install first)."
  exit 0
fi

PACKAGE_SWIFT="$PLUGIN_DIR/Package.swift"

cat > "$PACKAGE_SWIFT" <<'SWIFT'
// swift-tools-version: 5.9
// Auto-generated by scripts/patch-ios-spm-plugins.sh to add SPM support
// for capacitor-voice-recorder (which only ships a CocoaPods podspec upstream).
import PackageDescription

let package = Package(
    name: "CapacitorVoiceRecorder",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "CapacitorVoiceRecorder",
            targets: ["CapacitorVoiceRecorderPlugin"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", from: "8.0.0")
    ],
    targets: [
        .target(
            name: "CapacitorVoiceRecorderPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm")
            ],
            path: "ios/Plugin",
            exclude: ["Info.plist"],
            publicHeadersPath: "."
        )
    ]
)
SWIFT

echo "[patch-ios-spm-plugins] Wrote $PACKAGE_SWIFT"
